version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/frontend/node_modules
    environment:
      - VARNIKA_ENV=development
      - FLASK_SECRET_KEY=dev_secret_key
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev_jwt_secret}
      - PASSWORD_SALT=${PASSWORD_SALT:-dev_password_salt}
    command: python src/app.py
    restart: unless-stopped

  # For future use with a database
  # db:
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=varnika
  #     - POSTGRES_PASSWORD=varnika
  #     - POSTGRES_DB=varnika
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

  # For future use with Redis for caching
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

# For future use with a database
# volumes:
#   postgres_data:
